app = "new-project-test"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
PORT = "8080"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "rolling"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1
    soft_limit = 1

  [[services.http_checks]]
    interval = "15s"          # Как часто выполнять проверку
    timeout = "10s"           # Сколько ждать ответа
    grace_period = "30s"      # **ВАЖНО**: Подождать 30с после старта перед первой проверкой
    method = "get"
    path = "/"                # Проверять корневой путь
    protocol = "http"
    tls_skip_verify = true    # Если у вас нет валидного сертификата внутри контейнера