app = "new-project-test"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
PORT = "8080"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "rolling"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1
    soft_limit = 1
